name: http_signature_helper
description: Signature helpers from the HTTP Signature spec.
version: 1.0.1
homepage: https://github.com/Cretezy/http_signature_helper.dart
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  auth_params: ^1.0.0
  collection: ^1.14.0

dev_dependencies:
  test: ^1.0.0
